# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  ğŸ‘‹ Thanks for opening your first issue here! If you're reporting a ğŸ bug, please make sure you include steps to reproduce it. 
  We are a small team, and issues can pile up, so please be patient and we will get back to you as soon as we can.

  To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/andrewjmetzger/better-watchseries/blob/master/CONTRIBUTING.md).

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  ğŸ’– Thanks for opening this pull request! ğŸ’–
  
  We are a small team, and pull requests can pile up, so please be patient and we will get back to you as soon as we can.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰

# It is recommend to include as many gifs and emojis as possible
